name: Render htmls

on:
  push:
    branches: [ main ]

jobs:
  Job:
    runs-on: windows-latest
    steps:
      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action@v1.1.0
        with:
          path: README.md,CREDITS.md
          outputpath: out
